def load_data(school)
  section_a = Section.new("A")
  section_b = Section.new("B")

  student1 = Student.new("Ali")
  student1.set_marks("Math", 85.5)
  student1.set_marks("English", 90)
  student1.set_marks("Biology", 88)
  student1.set_marks("Chemistry", 92.5)
  student1.set_marks("Physics", 90)
  student1.set_marks("Urdu", 88)
  student1.set_marks("Islamic Studies", 92.5)

  student2 = Student.new("Ahmad")
  student2.set_marks("Math", 75.5)
  student2.set_marks("English", 60)
  student2.set_marks("Biology", 68)
  student2.set_marks("Chemistry", 52.5)
  student2.set_marks("Physics", 80)
  student2.set_marks("Urdu", 48)
  student2.set_marks("Islamic Studies", 72.5)

  student3 = Student.new("Rayan")
  student3.set_marks("Math", 75.5)
  student3.set_marks("English", 85)
  student3.set_marks("Biology", 54)
  student3.set_marks("Chemistry", 62.5)
  student3.set_marks("Physics", 80)
  student3.set_marks("Urdu", 68)
  student3.set_marks("Islamic Studies", 83.5)

  student4 = Student.new("Athar")
  student4.set_marks("Math", 83.5)
  student4.set_marks("English", 82)
  student4.set_marks("Biology", 38)
  student4.set_marks("Chemistry", 62.5)
  student4.set_marks("Physics", 50)
  student4.set_marks("Urdu", 68)
  student4.set_marks("Islamic Studies", 65.5)

  student5 = Student.new("Raees")
  student5.set_marks("Math", 85.5)
  student5.set_marks("English", 91)
  student5.set_marks("Biology", 58)
  student5.set_marks("Chemistry", 52.5)
  student5.set_marks("Physics", 70)
  student5.set_marks("Urdu", 58)
  student5.set_marks("Islamic Studies", 62.5)

  student6 = Student.new("Haider")
  student6.set_marks("Math", 85.5)
  student6.set_marks("English", 90)
  student6.set_marks("Biology", 78)
  student6.set_marks("Chemistry", 93.5)
  student6.set_marks("Physics", 60)
  student6.set_marks("Urdu", 68)
  student6.set_marks("Islamic Studies", 62.5)

  student7 = Student.new("Alsalan")
  student7.set_marks("Math", 85.5)
  student7.set_marks("English", 90)
  student7.set_marks("Biology", 88)
  student7.set_marks("Chemistry", 92.5)
  student7.set_marks("Physics", 90)
  student7.set_marks("Urdu", 88)
  student7.set_marks("Islamic Studies", 92.5)

  student8 = Student.new("Usama")
  student8.set_marks("Math", 75.5)
  student8.set_marks("English", 90)
  student8.set_marks("Biology", 58)
  student8.set_marks("Chemistry", 82.5)
  student8.set_marks("Physics", 50)
  student8.set_marks("Urdu", 78)
  student8.set_marks("Islamic Studies", 82.5)

  student9 = Student.new("Waheed")
  student9.set_marks("Math", 85.5)
  student9.set_marks("English", 80)
  student9.set_marks("Biology", 58)
  student9.set_marks("Chemistry", 58.5)
  student9.set_marks("Physics", 40)
  student9.set_marks("Urdu", 58)
  student9.set_marks("Islamic Studies", 64.5)

  student10 = Student.new("Mazz")
  student10.set_marks("Math", 55.5)
  student10.set_marks("English", 60)
  student10.set_marks("Biology", 58)
  student10.set_marks("Chemistry", 72.5)
  student10.set_marks("Physics", 40)
  student10.set_marks("Urdu", 88)
  student10.set_marks("Islamic Studies", 64.5)

  section_a.add_student(student1)
  section_a.add_student(student2)
  section_a.add_student(student3)
  section_a.add_student(student4)
  section_a.add_student(student5)
  section_b.add_student(student6)
  section_b.add_student(student7)
  section_b.add_student(student8)
  section_b.add_student(student9)
  section_b.add_student(student10)

  school.add_section(section_a)
  school.add_section(section_b)
end